#!/bin/bash

logvolume_int="/Library/StopChime/stopchime_logvolume_int"
logvolume_bool="/Library/StopChime/stopchime_logvolume_bool"

# reading the value stored in stopchime_logvolume
read value_int < "$logvolume_int"
read value_bool < "$logvolume_bool"

# restoring the volume state
# if was muted, nothing to do
# otherwise restore the volume level
if !$value_bool	then
	osascript -e 'set volume output muted false'
	osascript -e 'set volume output volume '$value_int''	
fi
